name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    # Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Build the project
    - name: Build
      run: npm run build

    # Run Jest tests
    - name: Run Tests
      run: npm test