name: CI

on: [push]

jobs:
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    # Next server
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
      working-directory: ./retrograde-dark-orbit

    # Run Jest tests
    - name: Run Tests
      run: npm run test
      working-directory: ./retrograde-dark-orbit

    # Socket server
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
      working-directory: ./server

    # Run Jest tests
    - name: Run Tests
      run: npm run test
      working-directory: ./server